apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx0
  labels:
    app: nginx0
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx0
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: nginx0
    spec:
      containers:
        - name: nginx0
          image: locationpocregistry.azurecr.io/nginx0:v1
          ports:
            - containerPort: 8080


#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: query-service
#spec:
#  replicas: 1
#  selector:
#    matchLabels:
#      app: query-service
#  template:
#    metadata:
#      labels:
#        app: query-service
#    spec:
#      containers:
#        - name: query-service
#          image: locationpocregistry.azurecr.io/query-service:v1
#          ports:
#            - containerPort: 8085