#apiVersion: v1
#kind: Service
#metadata:
#  name: query-service
#spec:
#  selector:
#    app: nginx0-deployment
#  ports:
#    - protocol: TCP
#      port: 80
#      targetPort: 8080
#  type: LoadBalancer

apiVersion: v1
kind: Service
metadata:
  name: query-lookup-service
spec:
  selector:
    app: query-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer