name: Build query service

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v2

      - uses: azure/docker-login@v1
        with:
          login-server: acrapmmpoc.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

##      - name: Build and Push Docker Image
#      - run: |
#         docker build -t acrapmmpoc.azurecr.io/query-service:latest .
##            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
#         docker push acrapmmpoc.azurecr.io/query-service:latest


      - run: |
          docker build . -t acrapmmpoc.azurecr.io/appdb:${{ github.sha }}
          docker push acrapmmpoc.azurecr.io/appdb:${{ github.sha }}

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS}}
          enable-AzPSSession: true

      - name: Set the AKS context
        run: az aks get-credentials --resource-group ${{ secrets.CLUSTER_RESOURCE_GROUP_NAME}} --name ${{ secrets.CLUSTER_NAME}}
      - name: Deploy to AKS
        run: kubectl apply -f kubernetes-manifests/





